function myFunction() {
    document.getElementById("Education").innerHTML = "Aenean euismod, ex vitae maximus hendrerit, ex dui semper nulla, sit amet maximus ante tortor malesuada nibh. Etiam vel scelerisque enim. In hac habitasse platea dictumst. Sed justo lectus, pretium in blandit id, rutrum vel tellus. Donec accumsan lectus vel orci tristique vehicula. Donec viverra, velit ut tristique lacinia, nibh lorem semper tortor, at dapibus justo felis varius arcu. Donec consequat eleifend sodales. Etiam volutpat, neque nec fermentum lacinia, lorem ante interdum dui, quis interdum lacus enim ac risus. Sed rutrum ullamcorper ultricies. Sed mollis vestibulum tortor eget tempus. Duis posuere convallis ex. Proin sed molestie justo. Vestibulum vitae neque sit amet nisl porta convallis quis non ex. Sed gravida, felis quis placerat laoreet, urna ipsum commodo felis, non lobortis libero risus sed est. Praesent nisl sem, maximus non nisl ut, posuere ornare erat.";
  }

  document.getElementById('home').addEventListener('click', function () {
    document.getElementById("Education").style.display = "none";});
